#!/usr/bin/python3
"""
"""
import os
import sys
from getopt import getopt
import re
import jinja2

BG = {}

root = os.path.dirname(os.path.abspath(__file__))
templates_dir = os.path.join(root, 'templates')
env = jinja2.Environment(loader=jinja2.FileSystemLoader(templates_dir))
template = env.get_template('default.html')
template2 = env.get_template('indice.html')


def gTree(n):
    nome = BG[n]['name']
    filho = []
    for i in BG[n]['fams']:
        for f in BF[i]['child']:
            filho.append((limpa(BG[f]['name']), f))
    return (limpa(nome), filho)


def procIndi(s, i):
    indi = {}
    v = re.search(r'\bNAME\s+(.*)', i)
    if v:
        indi['name'] = v[1]
    v = re.findall(r'\bFAMS\s+@(.*)@', i)
    indi['fams'] = v
    BG[s] = indi


BF = {}


def procFam(f, i):
    fam = {}
    h = re.search(r'\bHUSB\s+@(.*)@', i)
    if h:
        fam['husb'] = h[1]
    w = re.search(r'\bWIFE\s+@(.*)@', i)
    if w:
        fam['wife'] = w[1]
    fam['child'] = re.findall(r'\bCHIL\s+@(.*)@', i)
    BF[f] = fam


def procTexto(t):
    items = re.split(r'\n0', t)
    for i in items:
        z = re.search(r'@(I\d+)@ *INDI', i)
        if z:
            procIndi(z[1], i)
        f = re.search(r'@(F\d+)@ *FAM', i)
        if f:
            procFam(f[1], i)
#Funcao que remove todos os // e _ dos nomes
def limpa(t):
    t=re.sub(r"\_"," ",t)     #remove os _
    t=re.sub(r"\/+","",t)     #remove os / dos nomes
    return t


ops, args = getopt(sys.argv[1:], "a:o:")
ops = dict(ops)
for ficheiro in args:
    with open(ficheiro) as f:
        txt = f.read()
    procTexto(txt)
indice = []
for key, value in BG.items():
    filename = os.path.join(root, 'paginas', str(key) + ".html")
    indice.append([(limpa(BG[key]['name']), key)])
    f = gTree(key)
    nomes=f[1]
    #Adiciona um link para regressar ao inicio a todos os individuos
    nomes.append(("Voltar ao inicio","Index"))
    with open(filename, 'w') as fh:
        fh.write(template.render(
            h1=f[0],
            names=nomes
        ))
# Indice
filename = os.path.join(root, 'paginas', "Index.html")
with open(filename, 'w') as fh:
    fh.write(template2.render(
        h1="Indice",
        names=indice
    ))
