#!/usr/bin/python3
"""
"""
import os
import sys
from getopt import getopt
import re
import jinja2

BG = {}

root = os.path.dirname(os.path.abspath(__file__))
templates_dir = os.path.join(root, 'templates')
env = jinja2.Environment(loader=jinja2.FileSystemLoader(templates_dir))
template = env.get_template('default.html')


def gTree(n):
    nome = BG[n]['name']
    filho = []
    for i in BG[n]['fams']:
        for f in BF[i]['child']:
            filho.append(BG[f]['name'])
    return (nome, filho)


def procIndi(s, i):
    indi = {}
    v = re.search(r'\bNAME\s+(.*)', i)
    if v:
        indi['name'] = v[1]
    v = re.findall(r'\bFAMS\s+@(.*)@', i)
    indi['fams'] = v
    BG[s] = indi


BF = {}


def procFam(f, i):
    fam = {}
    h = re.search(r'\bHUSB\s+@(.*)@', i)
    if h:
        fam['husb'] = h[1]
    w = re.search(r'\bWIFE\s+@(.*)@', i)
    if w:
        fam['wife'] = w[1]
    fam['child'] = re.findall(r'\bCHIL\s+@(.*)@', i)
    BF[f] = fam


def procTexto(t):
    items = re.split(r'\n0', t)
    for i in items:
        z = re.search(r'@(I\d+)@ *INDI', i)
        if z:
            procIndi(z[1], i)
        f = re.search(r'@(F\d+)@ *FAM', i)
        if f:
            procFam(f[1], i)


ops, args = getopt(sys.argv[1:], "a:o:")
ops = dict(ops)
for ficheiro in args:
    with open(ficheiro) as f:
        txt = f.read()
    procTexto(txt)


for key, value in BG.items():
    filename = os.path.join(root, 'paginas', str(key) + ".html")

    f = gTree(key)
    with open(filename, 'w') as fh:
        fh.write(template.render(
            h1=f[0],
            names=f[1],
        ))
