#!/usr/bin/python3
"""
texto
    -sentence splitting
    -tokenizacao
    -tagging
    -named entity recognition (reconhece elementos numa frase, nomes de pessoas/locais/etc)
    -named entity classification (classifica nomes como local, pessoa,instituicao,etc)
    -parsing
        -shallow
        -dependency grammars 
        -...
    
"""
import sys
from getopt import getopt
import re
import spacy

txt=open(sys.argv[1]).read()
nlp=spacy.load("pt_core_news_sm")
a=nlp(txt)
#-------------------------------------------
for s in a.sents:
    if len(s.ents)>1:
        print ("========",s.ents)
        print (s)
#-------------------------------------------
#estudar math.lib
#calcular polaridade de um livro por capitulo