#!/usr/bin/python3
"""
texto
    -sentence splitting
    -tokenizacao
    -tagging
    -named entity recognition (reconhece elementos numa frase, nomes de pessoas/locais/etc)
    -named entity classification (classifica nomes como local, pessoa,instituicao,etc)
    -parsing
        -shallow
        -dependency grammars 
        -...
    
"""
import sys
from getopt import getopt
import re
import spacy

txt=open(sys.args[1]).read()
n=spacy.load("pt_core_news_sm")
a=n(txt)
#-------------------------------------------

#-------------------------------------------