#!/usr/bin/python3
# Necessario para o VSCode conseguir criar o gráfico
# %%
from matplotlib import pyplot as plt
import numpy as np
list = [10, 20, 30, 10]
cap = [1, 2, 3, 4]
plt.plot(cap, list)
plt.xlabel("Capitulos")
plt.ylabel("Polaridade")
plt.title('Positividade por capitulo')
plt.show()
# %%
