#!/usr/bin/python3
"""
Scraping
pip3 install requests
pip3 install beautifulsoup4

Da homepage do JN obter os varios links, titulos e tags das noticias
"""
import os
import sys
from getopt import getopt
import re
import requests
from bs4 import BeautifulSoup

r=requests.get("https://www.jn.pt")
soup=BeautifulSoup(r.text,features="html.parser")
pattern=r"jn.pt/\w+/"

def visit_noticia(url):
    r=requests.get(url)
    soup=BeautifulSoup(r.text,features="html.parser")
    content=soup.find('div',{'class':'t-article-content'})
    print(content.prettify(),"\n-----------------")


noticias=[]
articles=soup.find_all("article")
for article in articles:
    header=article.h3
    if header is None:
        continue
    url=header.a
    if url is None:
        continue
    url_address=url["href"]
    title=article.h2.a.text
    if url_address.startswith("http"):
        continue
    noticias.append((title,url_address))



for noticia in noticias:
    url='https://jn.pt'+ noticia[1]
    visit_noticia(url)